# Generated by Django 3.2.13 on 2022-06-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulete', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouleteRounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_id', models.IntegerField()),
                ('lucky_number', models.IntegerField()),
            ],
        ),
    ]
