# Generated by Django 3.2.13 on 2022-06-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulete', '0003_rouleterounds_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rouleterounds',
            name='lucky_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rouleterounds',
            name='round_id',
            field=models.IntegerField(null=True),
        ),
    ]
