# Generated by Django 3.2.13 on 2022-06-30 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roulete', '0004_auto_20220630_0834'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Members',
        ),
    ]
